services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: brain_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
  api:
    build: .
    container_name: brain_api
    ports:
      - "8001:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - COLLECTION_NAME=company_docs
      - MODEL_NAME=BAAI/bge-m3
    volumes:
      - hf_cache:/root/.cache/huggingface
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_data:
  hf_cache:
